language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: QvyOTfC4PPIaQWfPJS5IgKcV2GjEUIF3oleLPS7Iy8iblvzPTax8Bs4NfTKt9k1aVmLGyqKnrs8MDparQeWMkJ/B6k1l4CWWSelLI/GTc0Z63jKTTNVTGfyPAfJbNeApwND45eeG08582Bs3a+w7XS5DNvuvKfDPd5Fh6iKXzIGm3o1WBBxQPHcjsexPcs8QBnD1O0x6STmK4TkgDhGQPbH9EXpM+inxcIYvTgrmb2YklBAomJLTeaHCImtxtTpPffOSVCMOWFtd/zyRbuPxlyS7jMHoVbBX4HQ+pzmOzlsMBGTLfMJE8Wg3no9wRHOdqyMFDOlRu2jEydJ7RwdVCLkYzZu2d19WRKCur2BcLmJVuVE576NUctoAWJmmYQ0dSQtB8hgMoCNe3c4HcdPkiRD7yFhOgg0TckSwLA51+vrRYY0oK2cvCKpS9qEvEowa3VwLTFB3tDBsiHZYvdQMWY2/CfRxxWOpyJ4VluJACSShQqQHIDfGpRnFt5itqCl+MBk4n/oFi8gAyfgJeJBLsMSUlgonEVtxMucEeqoI9m3cfr1R118MGtcFk8oDADBLfMEdaMfFWDytiHzfWNbdpbNzbUK0vEcrjvHarEVLJElG6w7QlEaN4i/TFs1O4FL6+XemgXnPJMxzFvgCvzfFgtkRIprMqeVkqFrAOXEFeOw=

env:
  global:
    - secure: 0udobh+JEiL4k0eBGes+ipcdHd74KSrr9sLG8Cz0O/rlgW7mGXQ3fLu5ftT8aFt6Nf3h/dl/SrD7VUybYAFB7klFjYN/SHRRxvVoI8gS1dRI7qUHrmQokkaQKXWkcOCmDJQDSMQ7uUYbETM0NA2ZXxTtDAssCdIt3V8xjp7GyDGI+3aBeTjsLFNgU46iFHXDwncQ2VXp+Y2QKPGMpvxsb174qR5vvad9tb7sprCB5vmY7AV4NwrRMC3CB+W2SJIUpPXG4unLTURicC0gm5hC7UsAAW+4mUyZVq+zZNFgXhcRJrJuziosvNRneAwig+pvHkC4A3CmXO5nDPk8QuPKdbQ1NQ2BPXY92ITREY+0K8JjZfiuQTwxrNUKU6w2u2Ag0f+KBF4wlKpl7u6CjNvJl+oK5OvCarWxp4LSTNGkkanTmh14BL1ZHEJDJcK07ge0h/T7qvTQfnp8DChNPhFizwmx355cjZxiCiipBsYDP4gUmjbPB9+icSrkjBNf3jQd/5QVg89bQVZrvXiJ6PnOc4y6jVtRTJmdaZGyFxzwFrWfs18zn5ZL9QuCRVwuCjJUD14SO4zJnrnaKa/nwhmwdaiRtARCDP7pQKrINbQ3N/CMom6urniIqG9fSIZ+ViNYpKfoJDlrVG3lCoHhTJnEvr/iK/tFSJf/7zYvUGA+cMg=
    - secure: moKOhXYohMWGAIa2NjOtafUVY4aFktXV8llenJfSS3kB+DNtH1ANLFc+5aQa16bBR+mXzI4PXYTl5WzD2JXWUL3k63TAV8pNBWtS7Sc69VD8DAyffzZVyAqLgt/NJHP84jSzNv+YKMk/sRNgsCpEU6VT2gOu4wx80UHjdrCFU94K5JNJX/AqlrwTmEM2Qn3e6qN52KTcseWS/4x7o/VlI8ca8WZviPqoIcz6+KfFn5cROEB8QlOgfNGpJDCUkGNmNhYF9BJ3E4IYSDh+icEhnY+IqQzxEkV9IcIx5jDjqTEmD379b4V9zYcw4wcrmrR7dSMW3ydExcpy50Hjmvxb52eNtwO1R2Xdzf0sIfzkWEh6LdLifvr9vC8SrbDsP5TZb+K92OPEiX5jkaaoYKgfEXRrb3UTWGJX1IBxtfYJHNUii9T5PBIh2DSq/TtXorwCMwNpr1ph0Kkb47qPLZ+QifVrq6qgzcied67Nw4r1mHdUlqzZjIPKoY9o5l9M9SbUvZsu42n0BUfzpQEndeO8wGC3ep+UBdo/aKJ+zzO7oWpKmpEQp2O34QTZU4OQMnNQFnEw6LMr77iSadoxlEbo8GLnayJqdlGWHyPJjlO2bfwZhJg6JXaeUQwBQumPAgizTTXHh5ksLw6z+DURzdJBCk5kSiDVBNZCm0XRVszt9/c=
    - secure: 2WRG7JvsY3kQHEwh0YPuI2qI1Qx4Rq6NaRoeJZ99tL9+E0ZR/DTvD1LAQMEB6wYJkYyKi20W+gwxFRj9k2fN9HCbGYsm3IrhA4rhaReEtaxeKLQX9Zb2hoOFhCszdImpiJk6+fgoAFfBvd1RyWSdtYT0iyQmKF9zx7/xL//xi3lNvVS/w8rWP1gY+iFm4mpP+1iA/zbIbJl6tF15YUFdtZVxta7v3sRDO4z8qMDrwi/jplZbmkcINkpXLKzxUg+OFIxIR5uwIRFkoQq3PoGBhh6OlobbW0F4VvVvIRFoY3vcGFwIDrNyu67PhzeDj6NFA+iVfnNJdY3LpdwddBTybcY4Km7+4g/7gyycniopxQAFyMQS2z4vCZELeI7P7e91AMiLXPxvJeTT3saGvJZmDdjMVKZu0hUd15TjpGiadI2tjHVHEdUqhXSD2CtxttRjea4BdTvRYvcykGXU32/tNjgN/cH5eyIxilbjv4ZeXkC8CWpsXEGxdAJsBoA83FnNqFcZDcJrGJ4Z35vEukon4zIhupfXpuDKtbiyu40/OgB0rjWin13dimbChaZg6S85ARzC8iEEe6JDBEc503x9Symn1WGqpEDMThlFt0FIk45cuGGUY10FCW96nCc2chvreR2zEXdrz9HUJhLZaaC8DSMIL0qwMoiopkiXiKrLx6Y=
    - secure: G7LUbJkBJcmr1eS6Hyrw6PrhPDhh/DOW+tIgxSRur8VujPZHX/htUWqr24kIBQJTdZG03bjHZ7eE+hFqCGFU5Y96vh3oIPktC4Vc8Lu9RIpZhwZPC0opCiNX3iGlrYGwtQ1jRU2cNwJyw03vGEdnFFU47xoZMhoYiPuzHb4ua8uyAcmVQmaAT3bFdUcX5qjjTDsKKYzoEn4VhPkk8eW2sHeP7S8WpBASzi9MAco+ecSqseM2B1De2hdfVQ8eN+toZlxHqvvSDRigVO0vh5hlPeCVDGMbpmXoe5b9e7u4nrxePYXhXYvKyuNLvkZbkMOgEz0+suaXnLAgfhwhFxEbDUfj8fj02re+lEtkXplardDlq251xGiQkosnl+Hz81XSA9cBz4dIyoP86tw6P5rS2JV5A9/WnJNSdFukfIWGnWsER+XywZCrGTET6gO8p9NaSNkUBg60QfAN8rCMZdV1l6uDIQPWLaA87oaBHfVP79A+95WsOpV7F8GGqQAsgDjxq23VWbm37kpX4OIn7qAqQpG8Vm426PkZObgS6f6la/+FwTq2jUz+OchDXSrkuKQ81BCZsvShBuitYYY9+L0jKGWZRRCZCNW9TPHjKcM77mENAa/HiV3mOOzmlRVe2Z2MktWYBpb1Y8igrZ0glsS0KCtlt6tnGlEeXIOrRhjSErU=
    - secure: wkxCjmDPjoMlrUKgHLtHWULH5VFga++oHMgZmmyGlllIh0sTMAnlDnFTg+zgcXPOujTGg9Lqswv9Zhxwqc9ulKorr/PIn0DmRINAy5iOeJgRsv5A8EuII/suOxE8i7lfCc7vR+Dij+lmZZqUzurbQduy/+2Ofit63Xx6p1ixcB4bwOfRcK55fGByhKrAIeYhivN4NrlnBsXRvg0S13q+AO2hIeRZfQHvZ63Vb5A8g4ybSisHZEd89UgtxmUGX8hcuTWjJhHotpXVWpMNvrq3BTHPlTtDKvfaPmxqahYrPVZdWZ4Fu1j9Yd251E7ctifuhZn02FZwiH+NJVaKAYHe0JYXzgML7hDav7/RaPlolvwx6IM69F9qrmTcKuWBA8mLn7+3htXSAe/wttQl3gwzdweDv6i4vLXqctqSyugYDGz38KY9AXpMazADrDyKNQeX+gkAJFfc2S7RMDUTsYSVyq9Kr7Ny5wKv0XZ/gwL9/vp9ns2SbUX2Wl/c6MxrxRDmIqqAg5sgVbDvsbVBmcOF0uGUokJdymLLx3BrBFEadhH/ic7vNBx+ATevX/1TxtjipIHXV8bX3jwsqBJCxoPBNUkITXeo05q4ATBcdWNCxjR3ZRM70TfKVemHzERM4cu5qlnhOU6t0cLhZkq008cc98mQ1533mIyC8nezZUkC6LM=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn build:docker
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
